### ISSUE TITLE
Script fails on python 3.10.12

### ISSUE THREAD

**Issue by davidmann4** [Kremilly/Linkscraper#1]
**Describe the bug**
Basic commands failed.

* downloaded repo `git clone https://github.com/kremilly/linkscraper.git`
* pip install as mentioned in readme.md ( `pip install -r requirements.txt` )
* did basic command: `python linkscraper -u https://example.com -a get-links`
* script failed 

```
 _     _       _
| |   (_)_ __ | | _____  ___ _ __ __ _ _ __   ___ _ __
| |   | | '_ \| |/ / __|/ __| '__/ _` | '_ \ / _ \ '__|
| |___| | | | |   <\__ \ (__| | | (_| | |_) |  __/ |
|_____|_|_| |_|_|\_\___/\___|_|  \__,_| .__/ \___|_|
                                      |_|

------------------------------------------------------------
Homepage: https://github.com/Kremilly/linkscraper
------------------------------------------------------------
                v.2.5.1
------------------------------------------------------------
Target: https://example.com
Hostname: example.com
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dmann/workspace/linkscraper/linkscraper/__main__.py", line 52, in <module>
    Core.home(BASE_URL)
  File "/home/dmann/workspace/linkscraper/linkscraper/core/core.py", line 37, in home
    Layout.print("Scan:", cls.today_datetime(), "italic cyan")
TypeError: Core.today_datetime() takes 0 positional arguments but 1 was given
```

**Screenshots**
![image](https://github.com/kremilly/linkscraper/assets/1736570/128a65fc-880a-4df1-bf3a-1e063e464bed)

**Desktop (please complete the following information):**
 - windows with WSL ubuntu 
 
 
**Additional context**
looks like a cool project, would like to use it to find expired domains outbound links on a website

**Comment by Kremilly** [comment]
I fixed it! Thanks for report bug

**Comment by davidmann4** [comment]
ok cool, was about to install go for https://github.com/twiny/spidy

but let me give your script another run... 1 sec

**Comment by davidmann4** [comment]
works! thanks!
![image](https://github.com/kremilly/linkscraper/assets/1736570/3af772df-ceb6-43d4-a82a-bd9faf899ce1)


any idea how to use proxies with this script? I guess I could just use proxychains 

https://github.com/haad/proxychains

**Comment by Kremilly** [comment]
I'm considering adding proxy support, but it's a future consideration!

**Comment by davidmann4** [comment]
just noticed that the script does not follow any links? 

I would like to scrape an entire domain for all outgoing links to domains that I can buy. ( who is check) 

My guess is that i could use the domains for SEO Projects. 

Still thanks for your great work and support!

**Comment by Kremilly** [comment]
Unfortunately, this script does not currently follow any links.

Thanks for use the script and report the bugs ❤️

**Comment by davidmann4** [comment]
In the past I've used https://scrapy.org/ which is a python lib that allows you to scrape entire websites 

it already has proxy support and many other things
